# Server settings
serverHost: localhost
serverPort: 8080

# Database settings
databaseType: REDIS
databaseConfigs:
  REDIS:
    name: redis
    host: localhost
    port: 6379
    username:
    password:
  MONGODB:
    name: mongoDb
    host: localhost
    port: 27017
    username:
    password:

# Provider settings
oAuthProviderConfigs:
  GITHUB:
    accessTokenUrl:
    clientId:
    clientSecret:
    isEnabled: false

## Folder settings
materialsDestination: Materials
artifactsDestination: Artifacts

# Worker settings
# Min 1000; Max 30000
pipelineSchedulerPollInterval: 4000
materialTrackerPollInterval: 4000

