site_name: HawkCD
pages:
- Home: 'index.md'
- User Guide:
    - 'Writing your docs': 'user-guide/getting-started.md'
- Developers Guide:
    - 'Getting Started': 'developer-guide/getting-started.md'
    - 'Technology Stack': 'developer-guide/getting-started.md'
    - 'Architecture': 'developer-guide/getting-started.md'
- Requirements : srs.md
theme: united
